spring.application.name=lockmng

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/lockmng-db
spring.datasource.username=lockmng-db
spring.datasource.password=lockmng-db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=embedded
spring.sql.init.platform=postgres